=== dgonrom2803/DiegoGonzalez_UD4_LMSGI/PracticasCFGS/mejora.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
        version="0.1" xml:lang="es">
    <xs:element name="formulauno">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="piloto" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nombre" type="xs:string"/>
                            <xs:element name="codigoPiloto" type="xs:string"/>
                            <xs:element name="palmares" type="xs:string"/>
                            <xs:element name="observaciones" minOccurs="0" >
                                <xs:complexType mixed="true">
                                    <xs:sequence>
                                        <xs:element name="anhos" type="xs:string"/>
                                        <xs:element name="pais" type="xs:string"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                                <xs:choice>
                                    <xs:element name="instagram" type="xs:string"/>
                                    <xs:element name="twitter" type="xs:string"/>
                                </xs:choice>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== dgonrom2803/DiegoGonzalez_UD4_LMSGI/PracticasCFGS/mejora2.xml
<?xml version="1.0" encoding="UTF-8"?>
<formulauno xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="mejora.xsd">
	<piloto>
		<nombre>Fernando Alonso</nombre>
		<codigoPiloto>95555555K</codigoPiloto>
		<palmares>Campeón</palmares>
		<observaciones>Este piloto tiene <anhos>41</anhos>y es de<pais>España</pais></observaciones>
		<twitter>@alo_oficial</twitter>
		</piloto>
	<piloto>
		<nombre>Charles Leclerc</nombre>
		<codigoPiloto>44444444A</codigoPiloto>
		<palmares>No Campeón</palmares>
		<instagram>@charles_leclerc</instagram>
	</piloto>
</formulauno>
